version: '3.9'

services:
  mysql:
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "${DB_HOST}" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s
    image: mysql:8.0
    container_name: sber-mysql
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3307:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sber

  api:
    build: .
    container_name: sber-volunteer-api
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    command: [ "dotnet", "SberVolunteerAPI.dll" ]
    networks:
      - sber

volumes:
  mysql_data:

networks:
  sber: