// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SberVolunteerAPI.Models;

#nullable disable

namespace SberVolunteerAPI.Migrations
{
    [DbContext(typeof(SberVolunteerContext))]
    [Migration("20251210162558_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SberVolunteerAPI.Models.Event", b =>
                {
                    b.Property<uint>("IdEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("Id_event");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("IdEvent"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<uint>("CreatorId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("creator_id");

                    b.Property<DateTime>("DatetimeEnd")
                        .HasColumnType("datetime")
                        .HasColumnName("datetime_end");

                    b.Property<DateTime>("DatetimeStart")
                        .HasColumnType("datetime")
                        .HasColumnName("datetime_start");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_description");

                    b.Property<string>("EventState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('active','closed','cancelled')")
                        .HasColumnName("event_state")
                        .HasDefaultValueSql("'active'");

                    b.Property<string>("EventTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("event_title");

                    b.HasKey("IdEvent")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CreatorId" }, "creator_id");

                    b.HasIndex(new[] { "EventTitle" }, "event_title")
                        .IsUnique();

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("SberVolunteerAPI.Models.EventsToVolunteer", b =>
                {
                    b.Property<uint>("IdRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("Id_record");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("IdRecord"));

                    b.Property<uint>("IdEvent")
                        .HasColumnType("int unsigned")
                        .HasColumnName("Id_event");

                    b.Property<uint>("IdVolunteer")
                        .HasColumnType("int unsigned")
                        .HasColumnName("Id_volunteer");

                    b.Property<string>("RequestStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('pending','approved','rejected')")
                        .HasColumnName("request_status")
                        .HasDefaultValueSql("'pending'");

                    b.Property<string>("VisitStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('unknown','came','absent')")
                        .HasColumnName("visit_status")
                        .HasDefaultValueSql("'unknown'");

                    b.HasKey("IdRecord")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdEvent", "IdVolunteer" }, "Id_event")
                        .IsUnique();

                    b.HasIndex(new[] { "IdVolunteer" }, "Id_volunteer");

                    b.ToTable("events_to_volunteers", (string)null);
                });

            modelBuilder.Entity("SberVolunteerAPI.Models.User", b =>
                {
                    b.Property<uint>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("Id_user");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("IdUser"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("UserLogin")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_login");

                    b.Property<string>("UserMiddlename")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_middlename");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("enum('organiser','volunteer')")
                        .HasColumnName("user_role");

                    b.Property<string>("UserSurname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_surname");

                    b.Property<uint?>("VolunteersHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("volunteers_hours")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("IdUser")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserLogin" }, "user_login")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SberVolunteerAPI.Models.Event", b =>
                {
                    b.HasOne("SberVolunteerAPI.Models.User", "Creator")
                        .WithMany("Events")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("events_ibfk_1");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("SberVolunteerAPI.Models.EventsToVolunteer", b =>
                {
                    b.HasOne("SberVolunteerAPI.Models.Event", "IdEventNavigation")
                        .WithMany("EventsToVolunteers")
                        .HasForeignKey("IdEvent")
                        .IsRequired()
                        .HasConstraintName("events_to_volunteers_ibfk_1");

                    b.HasOne("SberVolunteerAPI.Models.User", "IdVolunteerNavigation")
                        .WithMany("EventsToVolunteers")
                        .HasForeignKey("IdVolunteer")
                        .IsRequired()
                        .HasConstraintName("events_to_volunteers_ibfk_2");

                    b.Navigation("IdEventNavigation");

                    b.Navigation("IdVolunteerNavigation");
                });

            modelBuilder.Entity("SberVolunteerAPI.Models.Event", b =>
                {
                    b.Navigation("EventsToVolunteers");
                });

            modelBuilder.Entity("SberVolunteerAPI.Models.User", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("EventsToVolunteers");
                });
#pragma warning restore 612, 618
        }
    }
}
